config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :students
  resources :grades
  resources :assignments
  resources :courses
  root to: "pages#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_navbar.html.erb
<nav>
  <ul>
    <li><%= link_to 'Home', root_path %> </li>
    <li><%= link_to 'Courses', courses_path %> </li>
    
    <% if current_user && current_user.admin %>
      <li><%= link_to 'Add Course', rails_admin.new_path('course') %> </li>
    <% end %>
    
    <li><%= link_to 'Grades', grades_path %> </li>
    
    <% if current_user && current_user.admin %>
      <li><%= link_to 'Add New Grade', rails_admin.new_path('grade') %> </li>
    <% end %>

    <li><%= link_to 'Assignments', assignments_path %> </li>
    
    <% if current_user && current_user.admin %>
      <li><%= link_to 'Add New Assignment', rails_admin.new_path('assignment') %> </li>
    <% end %>

    <li><%= link_to 'Students', students_path %> </li>

    <% if current_user && current_user.admin %>
      <li><%= link_to 'Add Students', rails_admin.new_path('student') %> </li>
    <% end %>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BetterLms</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <p class="navbar-text float-right">
    <%= render 'layouts/navbar' %>
    <% if user_signed_in? %>
      Logged in as <strong><%= current_user.email %></strong>.
      <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> 
      <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
    <% else %>
      <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
      <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
    <% end %>
    <%= yield %>
  </body>
</html>